# Generated by Django 5.2.8 on 2025-12-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nota_imdb', models.DecimalField(decimal_places=1, max_digits=3)),
                ('genero', models.CharField(choices=[('populares', 'Populares na Plataforma'), ('familia', 'Para Toda a Família'), ('terror', 'Aterrorizantes'), ('acao', 'Ação e Aventura'), ('independente', 'Cinema Independente')], max_length=20)),
                ('sinopse', models.TextField()),
                ('link_trailer', models.URLField()),
                ('capa', models.ImageField(upload_to='filmes/')),
                ('destaque', models.BooleanField(default=False)),
            ],
        ),
    ]
