# Generated by Django 5.2.8 on 2025-12-08 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_carrinho_itemcarrinho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmes', models.ManyToManyField(blank=True, to='main.filme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
